### ISSUE TITLE
just for exploring issues

### ISSUE THREAD

**Issue by kevit-ronak-jagani** [kevit-niket-bhadeshiya/workingTogether#3]
** There is one error in mihir.js**
@kevit-mihir-pithva

**Comment by kevit-mihir-pithva** [comment]
**### @kevit-ronak-jagani**  i am no longer a part on this project(workingTogether)

**Comment by kevit-ronak-jagani** [comment]
> **### @kevit-ronak-jagani** i am no longer a part on this project(workingTogether)

Ok as you wish @kevit-mihir-pithva
